# This is a basic workflow to help you get started with Actions

name: SpringBoot_toy_project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: master
  pull_request:
    branches: master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  S3_BUCKET_NAME : mygregbucket
  PROJECT_NAME : SpringBoot_toy_project

  # Steps represent a sequence of tasks that will be executed as part of the job
jobs: 
      build:
           runs-on: ubuntu-latest
           steps:
                - name : checkOut
                  uses: actions/checkout@v2
                - name : JDK
                  uses: actions/setup-java@v1 
                  with: 
                    java-version: 1.8  
                - name: Grant execute permission for gradlew 
                  run: chmod +x gradlew 
                  shell: bash 
                - name: Build with Gradle 
                  run: ./gradlew build 
                  shell: bash
                - name : Make zop File
                  run : zip -r ./$GITHUB_SHA.zip .
                  shell: bash
                - name : Configure AWS credentials
                  uses : aws-actions/configure-aws-credentials@v1
                  with :
                    aws-access-key-id: AKIA5W2IZCAUT56XROIW
                    aws-secret-access-key: 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
                    aws-region : ap-northeast-2
                - name : Upload to S3
                  run : aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$GITHUB_SHA.zip
